blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('post/<slug>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('edit/<slug>/', views.edit_post, name='edit_post'),
    path('delete/<slug>/', views.delete_post, name='delete_post'),
    path('comment_delete/<int:pk>', views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>', views.comment_edit, name='comment_edit'),
    path('like/<slug>', views.like, name='like'),
    path('dislike/<slug>', views.dislike, name='dislike'),
    path('comment_like/<int:pk>', views.comment_like, name='comment_like'),
    path('comment_dislike/<int:pk>', views.comment_dislike, name='comment_dislike'),
    path('reply/<int:pk>/', views.reply, name='reply')
]

top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace = 'blog')),
    path('users/', include(('users.urls','users'), namespace = 'users'))
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('log_in', views.log_in, name='log_in'),
    path('log_out', views.log_out, name='log_out'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import math

class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='image.jpg', blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)
    views = models.ManyToManyField(User, related_name='views', blank=True)
    saved = models.ManyToManyField(User, related_name='saved', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite', blank=True)
    comments_allowed = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.text[:20] + '...'
    
    def time_to_read(self):
        return math.ceil(len(self.text.split(' ')) / 100)



class Person(models.Model):
    name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    comment_likes = models.ManyToManyField(User, related_name='comment_likes')
    comment_dislikes = models.ManyToManyField(User, related_name='comment_dislikes')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='children')
    reply_to = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='reply')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Название поста'}), label='Название поста')
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea', 'size': 40, 'placeholder': 'Напишите текст поста'}), label='Текст поста')
    image = forms.ImageField(label='Картинка для поста', required=False)
    comments_allowed = forms.BooleanField(label='Комменты разрешены', widget=forms.CheckboxInput(), required=False)

    class Meta:
        model = Post
        fields = ['title', 'text', 'image', 'comments_allowed']


class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': "Оставьте ваш комментарий"
    }))

    class Meta:
        model = Comment
        fields = ['text', ]

blog/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import PostForm, CommentForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .utils import *
from django.core.paginator import Paginator


# def home(request):
#     posts = Post.objects.all()
#     search = request.GET.get('search')
#     query = request.GET.get('filter')
#     action = request.GET.get('action')

#     posts = filter_posts(query, request, posts) if query else posts

#     if action:
#         favorite_q = Post.objects.get(pk=request.GET.get('pk')).favorite
#         do_action(action, request, favorite_q)
#         return redirect('blog:home')

#     posts = posts.filter(
#         Q(title__icontains=search) |
#         Q(text__icontains=search)
#     ) if search else posts

#     return render(request, 'home.html', {'posts': posts})

def home(request):
    posts = Post.objects.all()
    search = request.GET.get('search')
    action = request.GET.get('action')
    query = request.GET.get('filter')

    from_date = request.GET.get('from')
    to_date = request.GET.get('to')

    posts = filter_posts(request, query, posts) if query else posts
    posts = posts.filter(
        date__range=[from_date, to_date]) if from_date else posts

    if action:
        if not request.user.is_authenticated:
            return redirect('users:log_in')

        do_action(action, request)
        return redirect('blog:home')

    posts = posts.filter(
        Q(title__icontains=search) |
        Q(text__icontains=search)
    ) if search else posts

    pages = Paginator(posts, 3)
    # Paginator по умоляанию принимает два параметра
    # 1) Список объектов, которые нуждаются в пагинации
    # 2) Колличество объектов на странице

    page = request.GET.get('page')
    # Узнаем текщею страницу

    posts = pages.get_page(page)
    # Сохраняем посты с выбранной страницы

    post_pages = posts.paginator.get_elided_page_range(
        posts.number, on_each_side=1, on_ends=1)
    # Нужен для более удобной пагинации с показом кнопок с нумерацией страниц.
    # Принимает три атрибута
    # 1) Номер текщей страницы
    # 2) Сколько показывать страниц с каждой стороны
    # 3) Сколько показывать страниц в конце

    return render(request, 'home.html', {'posts': posts, 'query': query, 'post_pages': post_pages})


# def post(request, slug):
#     post_detail = Post.objects.get(slug=slug)
#     form = CommentForm(request.POST or None)
#     action = request.GET.get('action')
#     if action:
#         do_action(action, request, post_detail.saved)
#         return redirect('blog:post', slug=slug)

#     if request.user not in post_detail.views.all():
#         post_detail.views.add(request.user)

#     if form.is_valid():
#         instance = form.save(commit=False)
#         instance.user = request.user
#         instance.post = post_detail
#         instance.save()
#         return redirect('blog:post', slug=slug)
#     return render(request, 'post.html', {'post': post_detail, 'form': form})


@login_required(login_url='/users/log_in')
def post(request, slug):
    post_detail = Post.objects.get(slug=slug)
    form = CommentForm(request.POST or None)
    action = request.GET.get('action')
    query = request.GET.get('filter')

    comments = post_detail.comment_set.filter(parent=None)

    comments = filter_comments( request, query, comments) if query else comments

    pages = Paginator(comments, 3)
    page = request.GET.get('page')
    comments = pages.get_page(page)

    comment_pages = comments.paginator.get_elided_page_range(comments.number)
    if action:
        add_saved(action, request)
        return redirect('blog:post', slug=slug)

    if request.user not in post_detail.views.all():
        post_detail.views.add(request.user)

    if form.is_valid():

        instance = form.save(commit=False)
        instance.user = request.user
        instance.post = post_detail

        instance.save()
        return redirect('blog:post', slug=slug)
    return render(request, 'post.html', {'post': post_detail, 'form': form, 'comment_pages': comment_pages, 'comments': comments, 'page': page, 'query': query})


@login_required(login_url='/users/log_in')
def create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        if Post.objects.last():
            instance.slug = request.POST.get(
                'title') + str(Post.objects.last().pk + 1)
        else:
            instance.slug = request.POST.get('title')
        instance.author = request.user
        instance.save()
        return redirect('blog:home')
    return render(request, 'create.html', {'form': form})


@login_required(login_url='/users/log_in')
def edit_post(request, slug):
    post_data = Post.objects.get(slug=slug)

    if request.user != post_data.author:
        return render(request, 'error.html', {'message': 'редактирование', 'object': 'поста'})

    form = PostForm(request.POST or None,
                    request.FILES or None, instance=post_data)
    # instance - зарезервированый аругмент формы. Подставляет значения из объекта
    if form.is_valid():
        form.save()
        return redirect('blog:post', slug=slug)
    return render(request, 'edit_post.html', {'form': form, 'post': post_data})


@login_required(login_url='/users/log_in')
def delete_post(request, slug):
    post_data = Post.objects.get(slug=slug)

    if request.user != post_data.author:
        return render(request, 'error.html', {'message': 'удаление', 'object': 'поста'})

    if request.method == 'POST':
        post_data.delete()
        return redirect('blog:home')
        # После удаления поста нужно перенаправить пользователя на главную страницу
    return render(request, 'delete_post.html', {'post': post_data})


@login_required(login_url='/users/log_in')
def comment_delete(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user != comment.user:
        return render(request, 'error.html', {'message': 'удаление', 'object': 'комментария'})

    if request.method == 'POST':
        comment.delete()
        if comment.parent:
            return redirect('blog:reply', pk=comment.parent.pk)
        return redirect('blog:post', slug=comment.post.slug)

    return render(request, 'delete_comment.html', {'comment': comment})


@login_required(login_url='/users/log_in')
def comment_edit(request, pk):
    comment = Comment.objects.get(pk=pk)
    form = CommentForm(request.POST or None, instance=comment)

    if request.user != comment.user:
        return render(request, 'error.html', {'message': 'редактирование', 'object': 'комментария'})

    if request.method == 'POST':
        form.save()
        if comment.parent:
            return redirect('blog:reply', pk=comment.parent.pk)
        return redirect('blog:post', slug=comment.post.slug)

    return render(request, 'edit_comment.html', {'comment': comment, 'form': form})


@login_required(login_url='/users/log_in')
def like(request, slug):
    post_data = Post.objects.get(slug=slug)

    if request.user not in post_data.likes.all():
        post_data.likes.add(request.user)
        post_data.dislikes.remove(request.user)
    else:
        post_data.likes.remove(request.user)

    return redirect('blog:post', slug=slug)


@login_required(login_url='/users/log_in')
def dislike(request, slug):
    post_data = Post.objects.get(slug=slug)

    if request.user not in post_data.dislikes.all():
        post_data.dislikes.add(request.user)
        post_data.likes.remove(request.user)
    else:
        post_data.dislikes.remove(request.user)

    return redirect('blog:post', slug=slug)


@login_required(login_url='/users/log_in')
def comment_like(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user not in comment.comment_likes.all():
        comment.comment_likes.add(request.user)
        comment.comment_dislikes.remove(request.user)
    else:
        comment.comment_likes.remove(request.user)

    reply_to = request.GET.get('to') 
    if reply_to:
        return redirect('blog:reply', pk= reply_to)
    return redirect('blog:post', slug=comment.post.slug) 


@login_required(login_url='/users/log_in')
def comment_dislike(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user not in comment.comment_dislikes.all():
        comment.comment_dislikes.add(request.user)
        comment.comment_likes.remove(request.user)
    else:
        comment.comment_dislikes.remove(request.user)
     
    reply_to= request.GET.get('to') 
    if reply_to:
        return redirect('blog:reply', pk= reply_to)
    return redirect('blog:post', slug=comment.post.slug)    


def reply(request, pk):
    replies = Comment.objects.filter(parent=pk)
    form = CommentForm(request.POST or None)
    parent = Comment.objects.get(pk=pk)
    reply_pk = request.POST.get('reply_pk')

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.post = parent.post
        instance.parent = parent
        if reply_pk:
            instance.reply_to = Comment.objects.get(pk=reply_pk)
        instance.save()
        return redirect('blog:reply', pk=pk)
    return render(request, 'reply.html', {'replies': replies, 'form': form, 'parent': parent})

blog/templates/create.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-5">
            <form class="box" method="post" action="{% url 'blog:create' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- {% csrf_token %} - токен безопасности отправки формы, обязательно надо писать перед созданием формы -->
                {% for field in form  %}
                    <div class="field">
                        {% if field.name != 'comments_allowed' %}
                        <label for="{{field.id_for_label}}" class="label">
                            {{field.label}}
                        </label>
                        {{field}}
                        {% else %}
                        <label for="{{field.id_for_label}}" class="checkbox">
                            {{field}}
                            {{field.label}}
                        </label>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="has-text-centered my-3">
                    <button type="submit" class="button is-success">
                        Отправить
                    </button>
                    <a href="{% url 'blog:home' %}" class="button is-danger"> Назад </a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/delete_comment.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="columns is-centered">
        <div class="column is-5">
            <form class="modal is-active" method="post">
                {% csrf_token %}
                <div class="modal-background"></div>
                <div class="modal-content">
                    <div class="box has-text-centered">
                        <div class="subtitle is-3">
                            Подтвердите удаление комментария
                        </div>
                        <button class="button is-danger">
                            Да
                        </button>
                        <a href="{% url 'blog:post' comment.post.slug %}" class="button is-success">
                            Нет
                        </a>

                    </div>
                </div>
                <button class="modal-close is-large" aria-label="close"></button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/delete_post.html
{% extends 'base_layout.html' %}

{% load static from static %}

{% block content %}

<form method="post" class="has-background-light">
    {% csrf_token %}
    <p class="title has-text-centered is-4 mb-5">
        Подтвердите удаление поста "{{ post }}"
    </p>
    <div class="has-text-centered">
        <button class="button is-danger">Подтвердить</button>
        <a class="button is-warning" href="{% url 'blog:post' post.slug %}">
            Назад к посту
        </a>
    </div>
</form>














{% endblock %}

blog/templates/edit_comment.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-5">
                <form class="box" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button class="button is-success mt-4">
                        Отредактировать
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/edit_post.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-5">
            <form method="post" class="box" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form  %}
                    <div class="field">
                        {% if field.name != 'comments_allowed' %}
                        <label for="{{field.id_for_label}}" class="label">
                            {{field.label}}
                        </label>
                        {{field}}
                        {% else %}
                        <label for="{{field.id_for_label}}" class="checkbox">
                            {{field}}
                            {{field.label}}
                        </label>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="has-text-centered">
                    <button class="button is-danger">Сохранить</button>
                    <a class="button is-warning" href="{% url 'blog:post' post.slug %}">
                        Назад к посту
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/error.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="columns is-centered is-vcentered">
            <div class="column is-5">
                <figure class="image">
                    <img src="{% static 'images/404.png' %}" alt="">
                </figure>
            </div>
            <div class="column is-4 has-text-centered">
                <div class="title is-2 has-text-white">
                    Упс! Похоже у вас нет прав на
                    {{ message }}
                    {{ object }}
                </div>
                <a href="{% url 'blog:home' %}" class="button is-info is-outlined is-inverted">
                    На главную
                </a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/post.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <div class="container"> 
        <div class="box has-text-centered" style="min-width: 100%">
            <div class="buttons is-right">
                <a href="{% url 'blog:post' post.slug %}?action=saved&pk={{post.pk}} " class="button is-info is-outlined">
                    {% if user in post.saved.all %}
                    <ion-icon name="save"></ion-icon>
                    {% else %}
                    <ion-icon name="save-outline"></ion-icon>
                    {% endif %}
                </a>
            </div>
            <div class="title has-text-black">
                {{ post }}
            </div>

            {% if post.image %}
                <img src="{{ post.image.url }}" alt="" class="image is-centered post-image is-fullwidth">
            {% else %}
                <img src="{% static 'images/image.jpg' %}" alt="" class="image is-centered post-image">
            {% endif %}
            <div class="subtitle has-text-black">
                {{ post.text }}
            </div>
            <div class="buttons">
                <a class="button {% if user in post.likes.all %} is-success {% endif %}" 
                href="{% url 'blog:like' post.slug %}">
                    <ion-icon name="thumbs-up"></ion-icon>
                </a>
                <a class="button {% if user in post.dislikes.all %} is-danger {% endif %}" 
                href="{% url 'blog:dislike' post.slug %}">
                    <ion-icon name="thumbs-down"></ion-icon>
                </a>
            </div>
            {% if user == post.author %}
                <div class="subtitle has-text-right">Опубликовано вами, {{ post.date }}</div>
            {% else %}

                <div class="subtile has-text-right">Опубликовано автором: {{ post.author }}, {{ post.date }}
                    <br><br>
                    <a href="{% url 'blog:home' %}?filter=author_post&user={{post.author.pk}}" 
                    class="button is-info is-outlined">Посмотреть все посты автора</a>
                </div>
            {% endif %}

        </div>
        {% if post.comments_allowed %}
        <div class="box">
            {% if post.comment_set.all %}
            <div class="is-flex is-align-items-center is-justify-content-space-between my-5">
                <div class="title">Комментарии читателей</div>
                <div class="buttons">
                    <a class="button is-info is-outlined  filter_comment" href="{% url 'blog:post' post.slug %}?filter=popular">Популярные</a>
                    <a class="button is-info is-outlined  filter_comment" href="{% url 'blog:post' post.slug %}?filter=old">Старые</a>
                    <a class="button is-info is-outlined  filter_comment" href="{% url 'blog:post' post.slug %}?filter=new">Новые</a>
                    <a class="button is-info is-outlined  filter_comment" href="{% url 'blog:post' post.slug %}?filter=my">Мои</a>
                </div>
            </div>
            {% else %}
                <div class="title">Пока нет комментариев</div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    {{field}}
                {% endfor %}
                <button class="button is-success mt-3">
                    Отправить
                </button>
            </form>
            <div class="columns is-centered is-multiline">
                {% for comment in comments %}
                    <div class="column is-4">
                        <div class="message is-info">
                            <div class="message-header">
                                От {{ comment.user }}
                                {% if request.user == comment.user %}
                                    <div class="buttons m-0 is-right">
                                        <a class="button m-0 ml-1 is-small is-info is-outlined is-inverted"
                                           href="{% url 'blog:comment_delete' comment.pk %}">
                                            <ion-icon name="trash-outline"></ion-icon>
                                        </a>
                                        <a class="button m-0 ml-1 is-small is-info is-outlined is-inverted"
                                           href="{% url 'blog:comment_edit' comment.pk %}">
                                            <ion-icon name="create-outline"></ion-icon>
                                        </a>
                                    </div>
                                    {% endif %}
                                    <div class="buttons m-0">
                                        <a 
                                        class="button is-small m-0 ml-1 {% if user in comment.comment_likes.all %} is-success {% endif %}" 
                                        href="{% url 'blog:comment_like' pk=comment.pk %}">
                                            <ion-icon name="thumbs-up"></ion-icon>
                                        </a>
                                        <a 
                                        class="button is-small m-0 ml-1 {% if user in comment.comment_dislikes.all %} is-danger {% endif %}" 
                                        href="{% url 'blog:comment_dislike' pk=comment.pk %}">
                                            <ion-icon name="thumbs-down"></ion-icon>
                                        </a>
                                    </div>
                            </div>
                            <div class="message-body has-text-centered">
                                {{ comment.text }}
                                <div class="buttons is-right">
                                    <a href="{% url 'blog:reply' comment.pk %}" 
                                        class="button is-rounded is-small replay-button" 
                                        onclick="toggleReplay(this.dataset.pk)">
                                        <ion-icon class="has-text-info" name="return-down-back-outline"></ion-icon>
                                    </a>
                                </div>
                                <div class="date-hover has-text-left">
                                    <div class="display none">
                                        {{ comment.date }}
                                        <br>
                                        {% if comment.children.count > 0 %}
                                            <a href="{% url 'blog:reply' comment.pk %}">Ответов: {{comment.children.count}}</a>
                                        {% endif %}
                                    </div>
                                </div>
                                
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if comments.has_other_pages %}
            <nav class="pagination is-centered">
                {% if comments.has_previous %}
                <a href="?page={{comments.previous_page_number}}" class="pagination-previous">
                    Назад
                </a>
                {% else %}
                <button class="pagination-previous has-text-white" disabled>Назад</button>
                {% endif %}

                {% if comments.has_next %}
                <a href="?page={{comments.next_page_number}}" class="pagination-next">
                    Далее
                </a>
                {% else %}
                <button class="pagination-next has-text-white" disabled>Далее</button>
                {% endif %}
                <ul class="pagination-list">
                    {% for page in comment_pages %}
                        <li>
                            <a 
                            href="{% if 'filter' in request.GET %}?page={{page}}&filter={{query}}{% else %}?page={{page}}{% endif %}" 
                            class="pagination-link {% if page == comments.number %} is-current {% endif %}">
                                {{page}}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock %}

blog/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    {% for i in posts %}
    <li>{{ i }}</li>
    {% endfor %}
    </ul>
</body>
</html>

blog/templates/reply.html
{% extends 'base_layout.html' %} {% block content %}
<div class="container">
  <div class="box">
    <div class="title">Ответ на комментарий: {{parent.user}}</div>
    <div class="my-2">
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="parent_pk" value="{{comment.pk}}" />
        {% for field in form %} {{field}} {% endfor %}
      </form>
    </div>
    <div style="height: 60vh; overflow-y: scroll;">
    {% for reply in replies %}
    <div class="box">
      <div class="has-text-right">
        <div class="dropdown is-hoverable is-right">
          <div class="dropdown-trigger">
            <ion-icon class="is-size-4" name="ellipsis-horizontal"></ion-icon>
          </div>
          <div class="dropdown-menu">
            <div class="dropdown-content has-text-left">
              <a class="dropdown-item" href="{% url 'blog:comment_edit' reply.pk %}">
                Отредактировать
              </a>
              <a class="dropdown-item" href="{% url 'blog:comment_delete' reply.pk %}">
                Удалить
              </a>
            </div>
          </div>
        </div>
      </div>
      {% if reply.reply_to %}
      <div class="subtitle has-text-info">
        В ответ {{ reply.reply_to }}
      </div>
      {% endif %}
      <div class="is-flex">
        <figure class="image is-48x48">
          <img
            class="is-rounded"
            src="https://bulma.io/images/placeholders/48x48.png"
            alt="" />
        </figure>
        <div class="subtitle m-2">
          {{reply.user}} &nbsp &nbsp
          <span class="has-text-gray-light is-size-6">{{reply.date}}</span>
          <br />
          <div class="content m-2">{{reply.text}}</div>
          <br>
          <button
            class="button is-small is-rounded"
            data-pk="{{reply.pk}}"
            onclick="toggleReply(this.dataset.pk)">
            <ion-icon name="return-down-forward-outline"></ion-icon>
          </button>
          <a href="{% url 'blog:comment_like' reply.pk %}?to={{ reply.parent.pk }}" class="button is-rounded is-small {% if user in reply.comment_likes.all %} is-success {% endif %}">
            <ion-icon name="thumbs-up"></ion-icon>
          </a>
          <a href="{% url 'blog:comment_dislike' reply.pk %}?to={{ reply.parent.pk }}" class="button is-rounded is-small {% if user in reply.comment_dislikes.all %} is-danger {% endif %}">
            <ion-icon name="thumbs-down"></ion-icon>
          </a>
        </div>
      </div>
      <div class="reply-{{reply.pk}} hidden my-2">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="reply_pk" value="{{ reply.pk }}" />
          {% for field in form %} {{field}} {% endfor %}
        </form>
      </div>
    </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}